export const ProductsData = [
  {
    id: 1,
    img: require("../img/nwhite.png"),
    name: "Air Max 90",
    brand: "Nike",
    price: 49.99,
    color: "white",
    background: "#dee2e6",
  },
  {
    id: 2,
    img: require("../img/agreen.png"),
    name: "Ultraboost",
    brand: "Adidas",
    price: 59.99,
    color: "green",
    background: "#20c997",
  },
  {
    id: 3,
    img: require("../img/nblack.png"),
    name: "Air Force 1",
    brand: "Nike",
    price: 669.99,
    color: "black",
    background: "#343a40",
  },
  {
    id: 4,
    img: require("../img/ablue.png"),
    name: "Stan Smith",
    brand: "Adidas",
    price: 239.99,
    color: "blue",
    background: "#0d6efd",
  },
  {
    id: 5,
    img: require("../img/nred.png"),
    name: "Kyrie Low",
    brand: "Nike",
    price: 369.99,
    color: "red",
    background: "#dc3545",
  },
  {
    id: 6,
    img: require("../img/ablack.png"),
    name: "Continental 80",
    brand: "Adidas",
    price: 99.99,
    color: "black",
    background: "#343a40",
  },

  {
    id: 7,
    img: require("../img/nyellow.png"),
    name: "gieefcs Run",
    brand: "Nike",
    price: 755.99,
    color: "yellow",
    background: "#ffc107",
  },

  {
    id: 8,
    img: require("../img/awhite.png"),
    name: "EQT Support",
    brand: "Adidas",
    price: 129.99,
    color: "white",
    background: "#dee2e6",
  },
  {
    id: 9,
    img: require("../img/ngreen.png"),
    name: "Renew Run",
    brand: "Nike",
    price: 456.99,
    color: "green",
    background: "#20c997",
  },
  {
    id: 10,
    img: require("../img/ared.png"),
    name: "React Vision",
    brand: "Adidas",
    price: 169.99,
    color: "red",
    background: "#dc3545",
  },
  {
    id: 11,
    img: require("../img/nblue.png"),
    name: "Flyknit Trainer",
    brand: "Nike",
    price: 369.99,
    color: "blue",
    background: "#0d6efd",
  },
  {
    id: 12,
    img: require("../img/ayellow.png"),
    name: "bbopj Vision",
    brand: "Adidas",
    price: 36.99,
    color: "yellow",
    background: "#ffc107",
  },
];
